### ISSUE TITLE
In-sim controls for custom blocks seem broken

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#140]
**Test device**
MacBook Pro
**Operating System**
MacOS 12.15
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/820. Seen in base sim as well as phet-io.
On the intro screen, switching a block to custom changes the mass of the block significantly and may even cause the mass to not match what is said on the slider. In addition, changing the mass slider changes the volume to the smallest available. It feels very buggy, can cause seemingly infinite bouncing on the water, and looks very strange.

**Visuals**
![bounce](https://user-images.githubusercontent.com/41024075/180496736-5a944699-6ce1-4146-ab97-0684dc277d70.gif)
![customsliders](https://user-images.githubusercontent.com/41024075/180496738-1a475a72-3d16-4654-820e-3f5bc22aaf3f.gif)

Troubleshooting information:

<detials>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.1.0-dev.2/phet/density_all_phet.html
Version: 1.1.0-dev.2 2022-07-18 21:07:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This did not happen in the published version.

**Comment by jonathanolson** [comment]
Broken in commit https://github.com/phetsims/density-buoyancy-common/commit/56093e1a86bc016b2e970b4ce13cc2288fcec9e4 (determined by bisection)

**Comment by jonathanolson** [comment]
I believe the above commit should fix this, but I'm concerned about regressions when switching to/from custom. @KatieWoe would you be able to test some cases on master?

**Comment by KatieWoe** [comment]
The volume change seems fixed, but the mass being wrong when you switch to custom, including making a small block bounce wildly, is still a problem.
![boing](https://user-images.githubusercontent.com/41024075/183467106-dbdcda56-c0d3-48e9-b2a5-22ccd9040731.gif)
![masswrong](https://user-images.githubusercontent.com/41024075/183467115-9fd9c8e5-30e7-4f16-952c-86271c9ff2ab.gif)

**Comment by KatieWoe** [comment]
After a quick check on master it looks fixed

**Comment by KatieWoe** [comment]
Things look ok to me in dev.3
