### ISSUE TITLE
Potential Performance issues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#70]
For https://github.com/phetsims/qa/issues/663. I did a quick memory test. While the memory test results look ok, I noticed some oddities with the fuzz test. The test seemed to stall often, with fuzzing seeming to stop for several seconds at a time. I also tried the fuzz test on iPad Safari (iPadOS 14) and the sim crashed and reloaded, which usually indicates a memory problem, though one doesn't seem to occur.
<img width="365" alt="memtest" src="https://user-images.githubusercontent.com/41024075/125365270-33fc2f80-e331-11eb-8264-6bc596644ec6.png">

**Comment by jonathanolson** [comment]
Screenshots are taking an impressive amount of time (over 50 seconds in my testing), those seem to be the causes of the stalls.

**Comment by jonathanolson** [comment]
Fixed some memory problems, and cut the screenshot time significantly with some optimizations. @KatieWoe can you test this out?

**Comment by KatieWoe** [comment]
I built a local version off of master on 7/29/21.The pauses still occurred, and did not seem to be connected to taking screenshots. However, the pause seemed a bit shorter and is now accompanied by this console error:
<img width="373" alt="errorsinfuzz" src="https://user-images.githubusercontent.com/41024075/127550501-3e69b793-c4b6-433c-afde-bfe1c2ce99e1.png">
Memory test:
<img width="364" alt="newmemtet" src="https://user-images.githubusercontent.com/41024075/127551335-ac19e819-1f1a-4263-aefc-7918aba35f5d.png">

**Comment by jonathanolson** [comment]
@KatieWoe are you able to take screenshots on your version (from the PhET menu?)

The above error looks like it's triggered by `Function.generateScreenshot`

**Comment by KatieWoe** [comment]
I thought by screenshots we were talking about the pause during fuzz while a memory snapshot was being made. I hadn't tried taking a screenshot from the menu.

**Comment by jonathanolson** [comment]
Taking screenshots from the menu is what used to take ~50 seconds on my system.

**Comment by KatieWoe** [comment]
I get this error when I try to take a screenshot.

**Comment by jonathanolson** [comment]
Added a mobius commit above, can you test and see if you get an error now when taking a screenshot?

**Comment by jonathanolson** [comment]
I believe the failure came from a non-integer backingScale (something that certain computers have and give to the browser). I believe it would have broken screenshots in built/unbuilt versions. I think it's fixed now, testing in the unbuilt version should be sufficient.

**Comment by KatieWoe** [comment]
I do not get a console error in master. Taking a screenshot takes a long amount of time however.

**Comment by jonathanolson** [comment]
I’m curious whether this performance is acceptable. Is a delay for the screenshot from the PhET menu acceptable?

**Comment by arouinfar** [comment]
It currently takes 12s to generate a screenshot on my MacBook, which is overly long. We can probably sacrifice some quality for speed, but this should be discussed with @kathy-phet and @DianaTavares, so tagging for design meeting.

**Comment by jonathanolson** [comment]
I'll make query parameters for tradeoffs (resolution and gamma correction).

**Comment by jonathanolson** [comment]
Query parameter docs:

```js
  // In screenshots or Canvas displays, what level of supersampling should be done (e.g. 3 results in 3x3 of pixels
  // being downscaled to 1 pixel).
  mobiusCanvasSupersampling: {
    type: 'number',
    defaultValue: 3
  },

  // Whether we should ignore gamma correction in supersampling (for screenshots and such)
  mobiusCanvasSkipGamma: {
    type: 'flag'
  }
```

So `?mobiusCanvasSupersampling=1&mobiusCanvasSkipGamma` is the fastest. `?mobiusCanvasSupersampling=3` is the default.

@DianaTavares can you try these out?

**Comment by DianaTavares** [comment]
I really find `?mobiusCanvasSupersampling=1&mobiusCanvasSkipGamma` good enough and super fast:

![Density screenshot (1)](https://user-images.githubusercontent.com/26031501/132748980-6cea19f8-f293-4cd7-844b-cfe3d8c18267.png)

I zoom in 400% and it looks a little pixelated, but I think it is good enough for students taking screenshots:

![image](https://user-images.githubusercontent.com/26031501/132749540-591ea433-d7b0-4414-bfea-c1676007fb0a.png)

**Comment by jonathanolson** [comment]
Should be made the default, can you verify master?

**Comment by DianaTavares** [comment]
The screenshot problem is solved! it is super fast like any other sim 

But I understand that a more general issue was identified by @KatieWoe when she run some tests (I am not sure that all this issue is just about the screenshot problem). @KatieWoe, can you verify that we can close this issue?

**Comment by KatieWoe** [comment]
Things look good in master. Closing
